### PR TITLE
Update example config file

### PR DESCRIPTION
**Pull request by ElectricFeet**
I'm still on this task (my timescales are absurd, I know; sorry!). I'm using the config files this time around to make it simpler (you need to use one in the end for Cron, so I decided to start the whole guide this way), but I'm confused by the example config, which seems out of date (or maybe i didn't understand:
- The "domains" parameter seems to need updating for 2.1
- The "public" parameter contained a file, not a directory (???)

### CODE REVIEW

**Comment by will-in-wi** [comment]
I'm a little confused by what you mean.

For domains, the syntax:
```yaml
domains:
  - 'example.com'
  - 'www.example.com'
```
and
```yaml
domains: ['example.com', 'www.example.com']
```
are identical and accomplish the same thing. I don't especially care which one is used, but I'm not sure what problem you ran into with the former.

As for `public`, I'm not sure what the difference is between `/home/myuser/webapps/myapp/public_html` and `/home/myuser/webapps/myapp` is. Presumably both point at directories. Also presumably, no one in the world has exactly this folder structure, so it'll need to be changed.


Either way, thanks for working on this. I'm starting to think that the day you get your documentation published will be the day that WebFaction finally releases first-party Let's Encrypt support. :p

As an aside, the test failures are due to some underlying changes to rubocop which I've fixed on master. You don't have to do so, but if you were to rebase, they would go away.

**Comment by ElectricFeet** [comment]
Oh cool! Thanks for the reply. It looks like I should have been asking questions, not changing stuff :-)

The differing formats were my misunderstanding that the two formats were equivalent. I'll go with the "[...]" format for my guide, as it matches the command line version so should cause less confusion for those who don't know YAML formats. 

The html was again my error. I read ".html", not "_html". My bad. Sorry.

As to the timescales: Ah, so this is a good news story! So far, I'm possibly faster than WebFaction :-)))))))

Thanks for your faith in my ability to deliver. Should be something RSN....

**Comment by will-in-wi** [comment]
Thanks much for working on all of this! I'm actually thinking your `['domain1', 'domain2']` syntax suggestion is an improvement, as anyone who knows array syntax in any other language will recognize it. If you want to submit a pull request with just that change, I'll merge it.

**Comment by ElectricFeet** [comment]
p.s. Why are the brackets needed in the config file but not on the command line?

**Comment by will-in-wi** [comment]
The config file is [YAML](http://yaml.org/), but the command line is comma separated: https://github.com/will-in-wi/letsencrypt-webfaction/blob/master/lib/letsencrypt_webfaction/args_parser/field.rb#L33

For the following code:
```ruby
val.split(',').map(&:strip).compact
```
`val` is expected to be a string, which is split by the comma character, and then each entry in resulting array is stripped of leading and trailing whitespace. Then the whole array has empty entries removed.

**Comment by ElectricFeet** [comment]
Thanks!

**Pull request closed without merging**
